### ISSUE TITLE
Div object has no attribute children

### ISSUE THREAD

**Issue by MHC03** [pyviz/panel#146]
I have a slightly more complex dashboard application, where I frequently get the following error: `Div object has no attribute children`. I tried to make a smaller application which duplicates the error. It is a dashboard with two tabs, the second has a column with just one empty HTML pane, I add and remove views to that column. My assumption is, that there is a problem with handling the HTML. Not quite sure, though.

The code should give some clarification to my explanation:

```python
import panel as pn
import holoviews as hv
import param
import numpy as np
hv.extension('bokeh', 'matplotlib')

class Options(param.Parameterized):
    slider1 = param.Range(default=(0, 100), bounds=(0, 200))
    slider2 = param.Range(default=(0, 1), bounds=(-10, 78))

class CorrelationBoard:
    
    def __init__(self):
        self.button = pn.widgets.Button(name='Start Plot')
        self.log_txt = pn.widgets.TextInput(name='Log:')
        self.options = Options()
        self._init_layout()
    
    def _init_layout(self):
        xs = np.linspace(0, np.pi*2)
        curve = hv.Curve((xs, np.sin(xs)))
        tabs = pn.Tabs(('Explore', curve), ('Detailed Plot', curve))
        options = pn.layout.WidgetBox(self.options, self.button, self.log_txt, width=400)
        self.layout = pn.Row(options, tabs, name='Histogram')   

class CroppingBoard:
    
    def __init__(self):
        self.load_button = pn.widgets.Button(name='Load Files')
        self.load_button.param.watch(self._load_data, 'clicks')
        self._init_layout()
        
    
    def _load_cropper(self):
        self.crop_button = pn.widgets.Button(name='Crop')
        self.crop_button.param.watch(self._load_views, 'clicks')
        self._add_cropping_layout()
    
    def _add_cropping_layout(self):
        if len(self.layout[0]) > 1:
            self.layout[0].objects = self.layout[0].objects[:1]
        self.layout.objects[0].append(self.crop_button)
    
    def _reset_views(self):
        self.second_tab.objects = self.second_tab.objects[:1]
    
    def _load_views(self, clicks):
        self._reset_views()
        column = self.cr_board.layout
        self.second_tab.append(column)   
    
    def _load_data(self, clicks):
        self.cr_board = CorrelationBoard()
        self._load_cropper()
        self._reset_views()
    
    def _init_layout(self):
        init_layout = pn.Column(pn.Row(self.load_button, name='Loader'), name='Loader')
        self.second_tab = pn.Column(pn.pane.HTML('', name='Columns Plot'), name='Columns Plot')
        self.layout = pn.Tabs(('Loader', init_layout), ('Columns Plot', self.second_tab))

CroppingBoard().layout.show()
```
A small gif for how to get the error:
![div_error](https://user-images.githubusercontent.com/22367686/48416763-5806ad80-e751-11e8-9d2c-c809fc08eb62.gif)

First Click `Load Files` then `Crop`, wait a bit and then click `Load Files` again.

Error message:

```python
ERROR:tornado.application:Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x000002200C8ADD90>, <Future finished exception=AttributeError("'Div' object has no attribute 'children'",)>)
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\tornado\ioloop.py", line 758, in _run_callback
    ret = callback()
  File "C:\Anaconda3\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\tornado\ioloop.py", line 779, in _discard_future_result
    future.result()
  File "C:\Anaconda3\lib\site-packages\tornado\gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "C:\Anaconda3\lib\site-packages\bokeh\server\session.py", line 51, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "C:\Anaconda3\lib\site-packages\bokeh\server\session.py", line 157, in with_document_locked
    return func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\bokeh\document\document.py", line 1076, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "C:\Anaconda3\lib\site-packages\bokeh\document\document.py", line 1062, in _with_self_as_curdoc
    return f()
  File "C:\Anaconda3\lib\site-packages\bokeh\document\document.py", line 1075, in invoke
    return f(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\bokeh\document\document.py", line 852, in remove_then_invoke
    return callback(*args, **kwargs)
  File "d:\panel\panel\layout.py", line 68, in update_model
    msg['objects'] = self._get_objects(model, old, doc, root, comm)
  File "d:\panel\panel\layout.py", line 127, in _get_objects
    pane._cleanup(old_child)
  File "d:\panel\panel\layout.py", line 86, in _cleanup
    p._cleanup(c, final)
  File "d:\panel\panel\layout.py", line 86, in _cleanup
    p._cleanup(c, final)
  File "d:\panel\panel\layout.py", line 85, in _cleanup
    for p, c in zip(self.objects, model.children):
AttributeError: 'Div' object has no attribute 'children'
```

**Comment by philippjfr** [comment]
Thanks, this has been on my to-do list to track down but having an issue for it will make sure I don't forget.

**Comment by philippjfr** [comment]
Should be fixed now.
