### ISSUE TITLE
FileInput broken with bokeh==1.3.0

### ISSUE THREAD

**Issue by ahuang11** [pyviz/panel#548]
```
import panel as pn
pn.extension()

pn.widgets.FileInput()
```
On upload, using the browser inspect:
```
Traceback (most recent call last):
  File "/users/huang/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/users/huang/anaconda3/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/users/huang/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "/users/huang/anaconda3/lib/python3.7/site-packages/bokeh/server/session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/users/huang/anaconda3/lib/python3.7/site-packages/bokeh/server/session.py", line 191, in with_document_locked
    return func(*args, **kwargs)
  File "/users/huang/anaconda3/lib/python3.7/site-packages/bokeh/document/document.py", line 1127, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/users/huang/anaconda3/lib/python3.7/site-packages/bokeh/document/document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "/users/huang/anaconda3/lib/python3.7/site-packages/bokeh/document/document.py", line 1126, in invoke
    return f(*args, **kwargs)
  File "/users/huang/anaconda3/lib/python3.7/site-packages/bokeh/document/document.py", line 916, in remove_then_invoke
    return callback(*args, **kwargs)
  File "/users/huang/anaconda3/lib/python3.7/site-packages/panel/viewable.py", line 653, in _change_event
    self.set_param(**self._process_property_change(events))
  File "/users/huang/anaconda3/lib/python3.7/site-packages/panel/widgets/input.py", line 59, in _process_property_change
    header, content = msg['value'].split(",", 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by philippjfr** [comment]
Ah, this is because bokeh does not allow more than one model to share the same name so it's now using the bokeh based FileInput model.
