### ISSUE TITLE
DatePicker value type error in Bokeh Server context

### ISSUE THREAD

**Issue by randomstuff** [pyviz/panel#555]
#### ALL software version info (Panel, bokeh, python, notebook, OS, browser, any other relevant packages)

* Debian testing
* Python 3.7.4
* `pip install panel`

<pre>
bokeh           1.3.0  
Jinja2          2.10.1 
Markdown        3.1.1  
MarkupSafe      1.1.1  
numpy           1.17.0 
packaging       19.0   
panel           0.6.0  
param           1.9.1  
Pillow          6.1.0  
pip             18.1   
pkg-resources   0.0.0  
pyct            0.4.6  
pyparsing       2.4.1.1
python-dateutil 2.8.0  
pyviz-comms     0.7.2  
PyYAML          5.1.1  
setuptools      40.8.0 
six             1.12.0 
tornado         6.0.3 
</pre>

#### Description of expected behavior and the observed behavior

When changing the value of a `Datepicker`, it fails with: `TypeError: 'datetime.date' object is not subscriptable`.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import panel.widgets as pnw
pnw.DatePicker().servable()
```

```sh
panel serve test.py
```

#### Stack traceback and/or browser JavaScript console output

<pre>
2019-07-29 10:08:31,618 Exception in callback functools.partial(<bound method IOLoop._discard_future_result of <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f5a885a7150>>, <Future finished exception=TypeError("'datetime.date' object is not subscriptable")>)
Traceback (most recent call last):
  File "/home/gcorona/temp/test/venv/lib/python3.7/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/gcorona/temp/test/venv/lib/python3.7/site-packages/tornado/ioloop.py", line 767, in _discard_future_result
    future.result()
  File "/home/gcorona/temp/test/venv/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
    yielded = self.gen.send(value)
  File "/home/gcorona/temp/test/venv/lib/python3.7/site-packages/bokeh/server/session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/home/gcorona/temp/test/venv/lib/python3.7/site-packages/bokeh/server/session.py", line 191, in with_document_locked
    return func(*args, **kwargs)
  File "/home/gcorona/temp/test/venv/lib/python3.7/site-packages/bokeh/document/document.py", line 1127, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/home/gcorona/temp/test/venv/lib/python3.7/site-packages/bokeh/document/document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "/home/gcorona/temp/test/venv/lib/python3.7/site-packages/bokeh/document/document.py", line 1126, in invoke
    return f(*args, **kwargs)
  File "/home/gcorona/temp/test/venv/lib/python3.7/site-packages/bokeh/document/document.py", line 916, in remove_then_invoke
    return callback(*args, **kwargs)
  File "/home/gcorona/temp/test/venv/lib/python3.7/site-packages/panel/viewable.py", line 653, in _change_event
    self.set_param(**self._process_property_change(events))
  File "/home/gcorona/temp/test/venv/lib/python3.7/site-packages/panel/widgets/input.py", line 118, in _process_property_change
    msg['value'] = datetime.strptime(msg['value'][4:], '%b %d %Y')
TypeError: 'datetime.date' object is not subscriptable
</pre>

**Comment by randomstuff** [comment]
I'll try to look at this. Could possibly be fixed with #507.

**Comment by randomstuff** [comment]
This seems to be working in notebook context.

**Comment by randomstuff** [comment]
This is related to a difference of implementation of the communication between the two cases (see `_link_params` in `viewable.py`). The bokeh server case uses the first branch and the notebook case uses the third one.

When going through Bokeh Server, Bokeh Server provides use with `date` values in it's callbacks:

```python
import panel.widgets as pnw
import panel as pn
from bokeh.models.widgets import DatePicker

picker = DatePicker()

def callback(attr, old, new):
    print("Attr: " + str(attr))
    print("Previous label: " + str(old) + " : " + str(type(old)))
    print("Updated label: " + str(new) + " : " + str(type(new)))
    print("---")

picker.on_change("value", callback)

pn.Row(picker).servable()
```

But the custom JS path uses string values.
