### ISSUE TITLE
RuntimeError: FileInput.filename is a readonly property

### ISSUE THREAD

**Issue by ericdill** [pyviz/panel#618]
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, ask us on [Gitter](https://gitter.im/pyviz/pyviz).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (Panel, bokeh, python, notebook, OS, browser, any other relevant packages)

* Anaconda Enterprise 5.3.0
* conda list output:
```
# packages in environment at /opt/continuum/anaconda/envs/dashboard:
#
_libgcc_mutex             0.1                        main    defaults
asn1crypto                0.24.0                   py37_0    defaults
attrs                     19.1.0                   py37_1    defaults
backcall                  0.1.0                    py37_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.0                    py37_0    defaults
bokeh                     1.3.4                    py37_0    defaults
ca-certificates           2019.5.15                     1    defaults
certifi                   2019.6.16                py37_1    defaults
cffi                      1.12.3           py37h2e261b9_0    defaults
chardet                   3.0.4                 py37_1003    defaults
cryptography              2.7              py37h1ba5d50_0    defaults
cycler                    0.10.0                   py37_0    defaults
dbus                      1.13.6               h746ee38_0    defaults
decorator                 4.4.0                    py37_1    defaults
defusedxml                0.6.0                      py_0    defaults
entrypoints               0.3                      py37_0    defaults
expat                     2.2.6                he6710b0_0    defaults
fontconfig                2.13.0               h9420a91_0    defaults
freetype                  2.9.1                h8a8886c_1    defaults
glib                      2.56.2               hd408876_0    defaults
gmp                       6.1.2                h6c8ec71_1    defaults
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
holoviews                 1.12.3                     py_2    defaults
icu                       58.2                 h9c2bf20_1    defaults
idna                      2.8                      py37_0    defaults
intel-openmp              2019.4                      243    defaults
ipykernel                 5.1.2            py37h39e3cac_0    defaults
ipython                   7.7.0            py37h39e3cac_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
jedi                      0.15.1                   py37_0    defaults
jinja2                    2.10.1                   py37_0    defaults
jpeg                      9b                   h024ee3a_2    defaults
jsonschema                3.0.2                    py37_0    defaults
jupyter_client            5.3.1                      py_0    defaults
jupyter_core              4.5.0                      py_0    defaults
kiwisolver                1.1.0            py37he6710b0_0    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libsodium                 1.0.16               h1bed415_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.0.10               h2733197_2    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libxcb                    1.13                 h1bed415_1    defaults
libxml2                   2.9.9                hea5a465_1    defaults
markdown                  3.1.1                    py37_0    defaults
markupsafe                1.1.1            py37h7b6447c_0    defaults
matplotlib                3.1.0            py37h5429711_0    defaults
mistune                   0.8.4            py37h7b6447c_0    defaults
mkl                       2019.4                      243    defaults
mkl-service               2.0.2            py37h7b6447c_0    defaults
mkl_fft                   1.0.14           py37ha843d7b_0    defaults
mkl_random                1.0.2            py37hd81dba3_0    defaults
nbconvert                 5.5.0                      py_0    defaults
nbformat                  4.4.0                    py37_0    defaults
ncurses                   6.1                  he6710b0_1    defaults
notebook                  6.0.0                    py37_0    defaults
numpy                     1.16.4           py37h7e9f1db_0    defaults
numpy-base                1.16.4           py37hde5b4d6_0    defaults
olefile                   0.46                     py37_0    defaults
openssl                   1.1.1c               h7b6447c_1    defaults
packaging                 19.1                     py37_0    defaults
pandas                    0.25.0           py37he6710b0_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py37_1    defaults
panel                     0.6.2                      py_0    https://conda.anaconda.org/pyviz
param                     1.9.1                      py_0    defaults
parso                     0.5.1                      py_0    defaults
pcre                      8.43                 he6710b0_0    defaults
pexpect                   4.7.0                    py37_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pillow                    6.1.0            py37h34e0f95_0    defaults
pip                       19.2.2                   py37_0    defaults
prometheus_client         0.7.1                      py_0    defaults
prompt_toolkit            2.0.9                    py37_0    defaults
ptyprocess                0.6.0                    py37_0    defaults
pycparser                 2.19                     py37_0    defaults
pyct                      0.4.6                    py37_0    defaults
pygments                  2.4.2                      py_0    defaults
pyopenssl                 19.0.0                   py37_0    defaults
pyparsing                 2.4.2                      py_0    defaults
pyqt                      5.9.2            py37h05f1152_2    defaults
pyrsistent                0.14.11          py37h7b6447c_0    defaults
pysocks                   1.7.0                    py37_0    defaults
python                    3.7.4                h265db76_1    defaults
python-dateutil           2.8.0                    py37_0    defaults
pytz                      2019.2                     py_0    defaults
pyviz_comms               0.7.2                      py_0    defaults
pyyaml                    5.1.2            py37h7b6447c_0    defaults
pyzmq                     18.1.0           py37he6710b0_0    defaults
qt                        5.9.7                h5867ecd_1    defaults
readline                  7.0                  h7b6447c_5    defaults
requests                  2.22.0                   py37_0    defaults
send2trash                1.5.0                    py37_0    defaults
setuptools                41.0.1                   py37_0    defaults
sip                       4.19.8           py37hf484d3e_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.29.0               h7b6447c_0    defaults
terminado                 0.8.2                    py37_0    defaults
testpath                  0.3.1                    py37_0    defaults
tk                        8.6.8                hbc83047_0    defaults
tornado                   6.0.3            py37h7b6447c_0    defaults
traitlets                 4.3.2                    py37_0    defaults
urllib3                   1.24.2                   py37_0    defaults
wcwidth                   0.1.7                    py37_0    defaults
webencodings              0.5.1                    py37_1    defaults
wheel                     0.33.4                   py37_0    defaults
xz                        5.2.4                h14c3975_4    defaults
yaml                      0.1.7                had09818_2    defaults
zeromq                    4.3.1                he6710b0_3    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.3.7                h0b5b093_0    defaults

```

#### Complete, minimal, self-contained example code that reproduces the issue
Notebook demonstrating this is [in this gist](https://gist.github.com/ericdill/a1d9059db64656569b4b6db810c1c4c3)

The workflow is:
1. create a FileInput widget
2. Use the FileInput widget to select a file
3. Try and render the FileInput widget again. (Rerendering the widget again happens regularly when you are trying to develop a dashboard with a FileInput widget, this is a contrived example that shows the stack trace)

#### Stack traceback and/or browser JavaScript console output
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~/anaconda/envs/dashboard/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj, include, exclude)
    968 
    969             if method is not None:
--> 970                 return method(include=include, exclude=exclude)
    971             return None
    972         else:

~/anaconda/envs/dashboard/lib/python3.7/site-packages/panel/viewable.py in _repr_mimebundle_(self, include, exclude)
    270         doc = _Document()
    271         comm = state._comm_manager.get_server_comm()
--> 272         model = self.get_root(doc, comm)
    273         if config.embed:
    274             embed_state(self, model, doc,

~/anaconda/envs/dashboard/lib/python3.7/site-packages/panel/viewable.py in get_root(self, doc, comm)
    398         """
    399         doc = doc or _curdoc()
--> 400         root = self._get_model(doc, comm=comm)
    401         self._preprocess(root)
    402         ref = root.ref['id']

~/anaconda/envs/dashboard/lib/python3.7/site-packages/panel/widgets/base.py in _get_model(self, doc, root, parent, comm)
     47 
     48     def _get_model(self, doc, root=None, parent=None, comm=None):
---> 49         model = self._widget_type(**self._process_param_change(self._init_properties()))
     50         if root is None:
     51             root = model

~/anaconda/envs/dashboard/lib/python3.7/site-packages/bokeh/model.py in __init__(self, **kwargs)
    305         kwargs.pop("id", None)
    306 
--> 307         super(Model, self).__init__(**kwargs)
    308         default_theme.apply_to_model(self)
    309 

~/anaconda/envs/dashboard/lib/python3.7/site-packages/bokeh/core/has_props.py in __init__(self, **properties)
    251 
    252         for name, value in properties.items():
--> 253             setattr(self, name, value)
    254 
    255     def __setattr__(self, name, value):

~/anaconda/envs/dashboard/lib/python3.7/site-packages/bokeh/core/has_props.py in __setattr__(self, name, value)
    278 
    279         if name in props or (descriptor is not None and descriptor.fset is not None):
--> 280             super(HasProps, self).__setattr__(name, value)
    281         else:
    282             matches, text = difflib.get_close_matches(name.lower(), props), "similar"

~/anaconda/envs/dashboard/lib/python3.7/site-packages/bokeh/core/property/descriptors.py in __set__(self, obj, value, setter)
    541 
    542         if self.property._readonly:
--> 543             raise RuntimeError("%s.%s is a readonly property" % (obj.__class__.__name__, self.name))
    544 
    545         self._internal_set(obj, value, setter=setter)

RuntimeError: FileInput.filename is a readonly property
```
#### Screenshots or screencasts of the bug in action
<img width="1196" alt="Screen Shot 2019-08-23 at 4 57 03 PM" src="https://user-images.githubusercontent.com/6223243/63623240-0e43d100-c5c7-11e9-986e-c6b9faf22b4f.png">

**Comment by philippjfr** [comment]
This was fixed, I'll release a new version asap.

**Comment by ltalirz** [comment]
Can I ask in which version this is fixed?
I tried installing v0.6.4a2 using `pip install git+https://github.com/pyviz/panel.git@v0.6.4a2` but this still seems to have the issue...

**Comment by philippjfr** [comment]
>I tried installing v0.6.4a2 using pip install git+https://github.com/pyviz/panel.git@v0.6.4a2 but this still seems to have the issue...

Really? I can't reproduce.

**Comment by ltalirz** [comment]
@philippjfr Thanks for the quick reply!

Reading through the exact issue description, perhaps the issue I'm seeing is a little different since it happens directly upon file upload (no reloading necessary), but it results in the same error message.

I have this in `submit/main.ipynb`
```python
import panel as pn

inp_cif = pn.widgets.FileInput()
column = pn.Column(inp_cif)
column.servable()
```
and then run `panel serve submit/`

When I upload a file, I get this error on the console:
```
2019-10-07 09:20:14,830 Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x118040400>, <tornado.concurrent.Future object at 0x1180092e8>)
Traceback (most recent call last):
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 626, in _discard_future_result
    future.result()
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/bokeh/server/session.py", line 70, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/bokeh/server/session.py", line 191, in with_document_locked
    return func(*args, **kwargs)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/bokeh/document/document.py", line 1127, in wrapper
    return doc._with_self_as_curdoc(invoke)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/bokeh/document/document.py", line 1113, in _with_self_as_curdoc
    return f()
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/bokeh/document/document.py", line 1126, in invoke
    return f(*args, **kwargs)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/bokeh/document/document.py", line 916, in remove_then_invoke
    return callback(*args, **kwargs)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/panel/viewable.py", line 673, in _change_event
    self.set_param(**self._process_property_change(events))
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/param/parameterized.py", line 1219, in inner
    return fn(*args, **kwargs)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/param/parameterized.py", line 2572, in set_param
    return self_or_cls.param.set_param(*args,**kwargs)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/param/parameterized.py", line 1365, in set_param
    self_._batch_call_watchers()
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/param/parameterized.py", line 1480, in _batch_call_watchers
    watcher.fn(*events)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/panel/viewable.py", line 624, in param_change
    self._update_model(events, msg, root, model, doc, comm)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/panel/viewable.py", line 604, in _update_model
    model.update(**msg)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/bokeh/core/has_props.py", line 376, in update
    setattr(self, k, v)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/bokeh/core/has_props.py", line 280, in __setattr__
    super(HasProps, self).__setattr__(name, value)
  File "/Users/leopold/Applications/miniconda3/lib/python3.6/site-packages/bokeh/core/property/descriptors.py", line 543, in __set__
    raise RuntimeError("%s.%s is a readonly property" % (obj.__class__.__name__, self.name))
RuntimeError: FileInput.filename is a readonly property
```

Output of pip freeze 
```
appnope==0.1.0
ase==3.18.1
attrs==19.2.0
backcall==0.1.0
bleach==3.1.0
bokeh==1.3.4
certifi==2019.9.11
chardet==3.0.4
# Editable install with no version control (cofdb-uploader==0.1.0)
-e /Users/leopold/Personal/Postdoc-MARVEL/Projects/2019-01-CoRE-COF-paper/updates/bokeh_app
crossrefapi==1.3.0
cycler==0.10.0
decorator==4.4.0
defusedxml==0.6.0
entrypoints==0.3
idna==2.8
ipykernel==5.1.2
ipython==7.8.0
ipython-genutils==0.2.0
jedi==0.15.1
Jinja2==2.10.3
jsmol-bokeh-extension==0.2.0
jsonschema==3.0.2
jupyter-client==5.3.3
jupyter-core==4.5.0
kiwisolver==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.1
mistune==0.8.4
nbconvert==5.6.0
nbformat==4.4.0
notebook==6.0.1
numpy==1.17.2
packaging==19.2
pandas==0.25.1
pandocfilters==1.4.2
panel==0.6.4a2
param==1.9.1
parso==0.5.1
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.2.0
prometheus-client==0.7.1
prompt-toolkit==2.0.10
ptyprocess==0.6.0
pyct==0.4.6
Pygments==2.4.2
pyparsing==2.4.2
pyrsistent==0.15.4
python-dateutil==2.8.0
pytz==2019.2
pyviz-comms==0.7.2
PyYAML==5.1.2
pyzmq==18.1.0
requests==2.22.0
scipy==1.3.1
Send2Trash==1.5.0
six==1.12.0
terminado==0.8.2
testpath==0.4.2
tornado==6.0.3
traitlets==4.3.3
urllib3==1.25.6
wcwidth==0.1.7
webencodings==0.5.1
```

**Comment by ltalirz** [comment]
After a reboot & re-entering the conda environment I cannot reproduce this anymore with 0.6.4a2 either. Sorry for the bother - and thanks for the fix!

**Comment by philippjfr** [comment]
Thanks for reporting back!
