### ISSUE TITLE
Interrupt background process in Panel

### ISSUE THREAD

**Issue by fmaussion** [pyviz/panel#710]
@pat-schmitt and I (well, mostly @pat-schmitt) are working on a glacier app which is very promising: https://github.com/pat-schmitt/glacier_simulator 

The app lets a user start numerical simulations, wait for the outcome and display the model results. A typical action on button click looks like:

```python
def run_model_equilibrium_button_click(arg=None):
    advance_model_click()
    run_the_model(stage='advance equilibrium')
``` 
where `run_the_model` can take up to a minute in the worst case (when the user enters certain parameter combinations). This might be frustrating to the user. Is there a way in Panel to interrupt such a process with an "interrupt" button? We are aware that this is probably not trivial but are willing to try something out if available.

Thanks!

**Comment by jbednar** [comment]
I assume that this can be done "by hand" with appropriate callbacks, but I think this capability would go hand in hand with progress bars, in that we need to have an easy and well-supported way to handle long-running actions. Here, what I would like to see is the notion of an action with a progress bar (if progress is measurable) or at least a spinner (otherwise), along with a cancel button.

**Comment by philippjfr** [comment]
Suspect this would only be possible if the task is fired off in a separate thread since Bokeh server will probably not accept new events until the last one has been processed otherwise.

**Comment by pat-schmitt** [comment]
I have tried to use the `threading` package of the python standard library, but this only works for my app when the app is only executed in an jupyter notebook, but not when called with the `.show()` statement. But i have just wrote a mini example how i made it and there it works also with `.show()`. 

`import panel as pn
import holoviews as hv
from holoviews import opts
from holoviews.streams import Stream, param
import threading
import time

pn.extension()
hv.extension('bokeh', width=100)

stop_model_flag = False
x_curve = [0]
y_curve = [0]
output_curve = []
dmap_change_flag = True


def start_button_click(arg=None):
    model_run = threading.Thread(target=run_the_model)
    model_run.start()


start_button = pn.widgets.Button(name='start')
start_button.param.watch(start_button_click, 'clicks')


def stop_button_click(arg=None):
    global stop_model_flag
    stop_model_flag = True


stop_button = pn.widgets.Button(name='stop')
stop_button.param.watch(stop_button_click, 'clicks')



def set_output_curve():
    global output_curve
    output_curve = hv.Curve((x_curve, y_curve),
                            'x_label',
                            'y_label').opts(opts.Curve(framewise=True))


set_output_curve()


def run_the_model():
    global x_curve, y_curve
    global dmap_change_flag
    global stop_model_flag

    loop_index = 0
    while loop_index < 10:
       # simulate model calculation
        time.sleep(1)
        x_curve.append(x_curve[-1] + 1)
        y_curve.append(y_curve[-1] + 1)
        loop_index += 1

        set_output_curve()

        dmap_change_flag = not dmap_change_flag
        dmap.event(change=dmap_change_flag)
        
        if stop_model_flag:
            stop_model_flag = False
            break


def dmap_function(change=True):
    return output_curve


dmap_stream = Stream.define('dmap_stream', change=True)
dmap = hv.DynamicMap(dmap_function, streams=[dmap_stream()])

pn.Column(pn.Row(start_button, stop_button), dmap).show()`

Maybe in my app i have some issues with the model run itself or some other stuff, I have to check. But if someone is more experienced with creating separate thread i would appreciate some ideas or links where i can read more.

Thank you anyway, I find holoviz as a whole very useful and a cool tool to use

**Comment by philippjfr** [comment]
Note that the `.show` method actually accepts a `threaded` argument.

**Comment by pat-schmitt** [comment]
I tried the stopping approach presented above again and finally found a possible reason why it is not working (in the 'large' app). The problem is I think that when the dynamic map is getting more complicated the event to change it takes some time and in the meanwhile the model run is continuing and tries to update the dynamic map again, even when the previous update has not finished.

So I created a new mini example illustrating the problem:

Software versions:
panel 0.11.1
holoviews 1.14.2
bokeh 2.3.0
tornado 6.1

```
import panel as pn
import holoviews as hv
from holoviews import opts
from holoviews.streams import Stream
import time
import numpy as np
import threading

pn.extension()
hv.extension('bokeh', width=100)

# define number of polygons
nr_of_polygons = 10

# defind initial data for polygons
polygon_data = np.arange(nr_of_polygons)

# flag to stop model run
stop_model_run = False

# function for creation of result figure
def set_result_polygon():
    global result_polygon
    result_polygon = hv.Polygons([{('x', 'y'): hv.Box(0, 0, i).array(),
                                   'z': polygon_data[i]} for i in range(nr_of_polygons)[::-1]],
                                 vdims='z'
                                 ).opts(responsive=True,
                                        aspect=1)

set_result_polygon()

# define dynamic map
dmap_change_flag = True

def dmap_function(change=True):
    return result_polygon

dmap_stream = Stream.define('dmap_stream', change=True)
dmap = hv.DynamicMap(dmap_function, streams=[dmap_stream()])

# function for simulating model run
def run_the_model():
    global dmap_change_flag
    global stop_model_run
    global polygon_data

    while True:
        if stop_model_run:
            break

        # simulate model calculation
        time.sleep(0.1)
        polygon_data = np.roll(polygon_data, 1)

        # set the new data
        set_result_polygon()

        # change the dynamic map to show new data
        dmap.event(change=dmap_change_flag)
        dmap_change_flag = not dmap_change_flag
        # give program time to update figure
        # time.sleep(0.5)

    stop_model_run = False
    toggle_buttons()


# define buttons
def toggle_buttons():
    start_button.disabled = not start_button.disabled
    stop_button.disabled = not stop_button.disabled

start_button = pn.widgets.Button(name='start',
                                 button_type='success')

def start_button_click(event):
    toggle_buttons()
    model_run = threading.Thread(target=run_the_model)
    model_run.start()

start_button.on_click(start_button_click)

stop_button = pn.widgets.Button(name='stop',
                                button_type='danger',
                                disabled=True)

def stop_button_click(event):
    global stop_model_run
    stop_model_run = True


stop_button.on_click(stop_button_click)

# actual app
pn.Column(start_button,
          stop_button,
          dmap,
          width=500,
          ).show()
```


As the code is after letting the model run for some undefined time I get the following Exception:

```
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/panel/io/server.py", line 371, in unlocked
    WebSocketHandler.write_message(socket, msg.header_json)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/tornado/websocket.py", line 340, in write_message
    return self.ws_connection.write_message(message, binary=binary)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/tornado/websocket.py", line 1096, in write_message
    fut = self._write_frame(True, opcode, message, flags=flags)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/tornado/websocket.py", line 1073, in _write_frame
    return self.stream.write(frame)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/tornado/iostream.py", line 540, in write
    future = Future()  # type: Future[None]
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-9'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-4-72954098c52f>", line 65, in run_the_model
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/holoviews/core/spaces.py", line 1076, in event
    Stream.trigger(streams)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/holoviews/streams.py", line 186, in trigger
    subscriber(**dict(union))
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/holoviews/plotting/plot.py", line 244, in refresh
    raise e
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/holoviews/plotting/plot.py", line 240, in refresh
    self._trigger_refresh(stream_key)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/holoviews/plotting/plot.py", line 257, in _trigger_refresh
    self.update(key)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/panel/io/server.py", line 382, in unlocked
    curdoc.unhold()
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/bokeh/document/document.py", line 669, in unhold
    self._trigger_on_change(event)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/bokeh/document/document.py", line 1185, in _trigger_on_change
    self._with_self_as_curdoc(invoke_callbacks)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/bokeh/document/document.py", line 1184, in invoke_callbacks
    cb(event)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/bokeh/document/document.py", line 724, in <lambda>
    self._callbacks[receiver] = lambda event: event.dispatch(receiver)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/bokeh/document/events.py", line 269, in dispatch
    super().dispatch(receiver)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/bokeh/document/events.py", line 124, in dispatch
    receiver._document_patched(self)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/bokeh/server/session.py", line 218, in _document_patched
    raise RuntimeError("_pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes")
RuntimeError: _pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes
```


Further when changing the numbers of shown polygons to 100 (`nr_of_polygons = 100`) I get a slightly different Exception:

```
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/holoviews/plotting/bokeh/element.py", line 1460, in _update_glyphs
    self._update_glyph(renderer, properties, mapping, glyph, source, data)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/holoviews/plotting/bokeh/element.py", line 1285, in _update_glyph
    self._update_datasource(source, data)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/holoviews/plotting/bokeh/plot.py", line 165, in _update_datasource
    source.data.update(data)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/bokeh/core/property/wrappers.py", line 378, in update
    descriptor._notify_mutated(owner, old, hint=hint)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/bokeh/core/property/descriptors.py", line 886, in _notify_mutated
    self._real_set(obj, old, value, hint=hint)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/bokeh/core/property/descriptors.py", line 849, in _real_set
    self._trigger(obj, old, value, hint=hint, setter=setter)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/bokeh/core/property/descriptors.py", line 926, in _trigger
    obj.trigger(self.name, old, value, hint, setter)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/bokeh/model.py", line 682, in trigger
    super().trigger(descriptor.name, old, new, hint=hint, setter=setter)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/bokeh/util/callback_manager.py", line 163, in trigger
    self._document._notify_change(self, attr, old, new, hint, setter, invoke)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/bokeh/document/document.py", line 1090, in _notify_change
    self._trigger_on_change(event)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/bokeh/document/document.py", line 1185, in _trigger_on_change
    self._with_self_as_curdoc(invoke_callbacks)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/bokeh/document/document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/bokeh/document/document.py", line 1184, in invoke_callbacks
    cb(event)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/bokeh/document/document.py", line 724, in <lambda>
    self._callbacks[receiver] = lambda event: event.dispatch(receiver)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/bokeh/document/events.py", line 269, in dispatch
    super().dispatch(receiver)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/bokeh/document/events.py", line 124, in dispatch
    receiver._document_patched(self)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/bokeh/server/session.py", line 218, in _document_patched
    raise RuntimeError("_pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes")
RuntimeError: _pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-8-2f670083be23>", line 59, in run_the_model
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/holoviews/core/spaces.py", line 1076, in event
    Stream.trigger(streams)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/holoviews/streams.py", line 186, in trigger
    subscriber(**dict(union))
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/holoviews/plotting/plot.py", line 244, in refresh
    raise e
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/holoviews/plotting/plot.py", line 240, in refresh
    self._trigger_refresh(stream_key)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/holoviews/plotting/plot.py", line 257, in _trigger_refresh
    self.update(key)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/holoviews/plotting/plot.py", line 983, in update
    item = self.__getitem__(key)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/holoviews/plotting/plot.py", line 446, in __getitem__
    self.update_frame(frame)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/holoviews/plotting/bokeh/element.py", line 1536, in update_frame
    self._update_glyphs(element, ranges, self.style[self.cyclic_index])
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/holoviews/plotting/bokeh/element.py", line 1460, in _update_glyphs
    self._update_glyph(renderer, properties, mapping, glyph, source, data)
  File "/home/patrick/miniconda3/envs/oggm_env/lib/python3.8/site-packages/holoviews/core/options.py", line 227, in __exit__
    raise AbbreviatedException(etype, value, traceback)
holoviews.core.options.AbbreviatedException: RuntimeError: _pending_writes should be non-None when we have a document lock, and we should have the lock when the document changes

To view the original traceback, catch this exception and call print_traceback() method.
```
Both exceptions have the same origin (locking of bokeh document) and they can be avoided by given the dynamic map time to change (uncomment `time.sleep(0.5)` below dynamic map event). However this is not a very good/robust solution.

Maybe something like the `threading` `.join()` is needed to wait for the dynamic map to finish the update before contiouing the model run, or to queue the updates in some way to save computing time and let the model run continue. But I could not found a satisfactory solution.

**Comment by Coderambling** [comment]
Hi @fmaussion . Just came across your issue by chance. A lot has happened in Panel since this issue :-)

Would the following help?

https://panel.holoviz.org/how_to/callbacks/load.html . This guide addresses how to defer and orchestrate long running background tasks with pn.state.onload. You can use this to improve the user experience of your app.

https://panel.holoviz.org/how_to/callbacks/async.html

https://panel.holoviz.org/how_to/interactivity/bind_generators.html

https://panel.holoviz.org/how_to/concurrency/index.html

https://panel.holoviz.org/how_to/interactivity/bind_generators.html . How to use yield.
