### ISSUE TITLE
Scipy now required dependency?

### ISSUE THREAD

**Issue by sdc50** [pyviz/panel#720]
The latest dev build of panel (panel-0.7.0a15-py_0) looks like it is trying to import scipy, but scipy is not among the required dependencies that are automatically installed through conda.

```
$ conda create -n panel -c pyviz/label/dev panel
...
$ conda activate panel
(panel) $ python
Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import panel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rditlsc9/miniconda/envs/panel/lib/python3.7/site-packages/panel/__init__.py", line 6, in <module>
    from . import links # noqa
  File "/Users/rditlsc9/miniconda/envs/panel/lib/python3.7/site-packages/panel/links.py", line 12, in <module>
    from .pane.holoviews import HoloViews, generate_panel_bokeh_map, is_bokeh_element_plot
  File "/Users/rditlsc9/miniconda/envs/panel/lib/python3.7/site-packages/panel/pane/__init__.py", line 13, in <module>
    from .holoviews import HoloViews # noqa
  File "/Users/rditlsc9/miniconda/envs/panel/lib/python3.7/site-packages/panel/pane/holoviews.py", line 20, in <module>
    from ..widgets import Player
  File "/Users/rditlsc9/miniconda/envs/panel/lib/python3.7/site-packages/panel/widgets/__init__.py", line 12, in <module>
    from .misc import Audio, VideoStream # noqa
  File "/Users/rditlsc9/miniconda/envs/panel/lib/python3.7/site-packages/panel/widgets/misc.py", line 14, in <module>
    from scipy.io import wavfile
ModuleNotFoundError: No module named 'scipy'
```

**Comment by philippjfr** [comment]
That's poor review from me, this should not be imported at the top-level. I'll push a fix shortly.
