### ISSUE TITLE
Cannot install and run panel-examples without errors

### ISSUE THREAD

**Issue by MarcSkovMadsen** [pyviz/panel#781]
#### ALL software version info (Panel, bokeh, python, notebook, OS, browser, any other relevant packages)

Panel: 0.6.4
Bokeh: 1.3.4
Python: Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
notebook:  6.0.1
browser: Chrome

#### Description of expected behavior and the observed behavior

I would expect to be able to `pip install panel`, install the panel-examples and `serve` them without errors.

#### Complete, minimal, self-contained example code that reproduces the issue

```bash
$ pip install panel
```

### Error 1:  _tkinter.TclError: can't invoke "wm" command:  ###

```bash
$ cd panel-examples/getting_started
$ panel serve --show Introduction.ipynb
2019-11-14 05:27:48,797 Starting Bokeh server version 1.3.4 (running on Tornado 6.0.3)
2019-11-14 05:27:48,805 Bokeh app running at: http://localhost:5006/Introduction
2019-11-14 05:27:48,805 Starting Bokeh server with process id: 10864
Column
    [0] Column
        [0] FloatSlider(end=3.0, name='frequency', start=-1.0, value=1.0)
        [1] FloatSlider(end=3.0, name='amplitude', start=-1.0, value=1.0)
        [2] IntSlider(end=100, name='n', start=5, value=200)
    [1] Row
        [0] Matplotlib(Figure, name='interactive00015')
2019-11-14 05:27:53,209 Error running application handler <bokeh.application.handlers.notebook.NotebookHandler object at 0x0000000996DA1388>: can't invoke "wm" command: application has been destroyed
File "__init__.py", line 1841, in wm_geometry:
return self.tk.call('wm', 'geometry', self._w, newGeometry) Traceback (most recent call
last):
  File "c:\repos\private\awesome-analytics-apps-in-python\.venv\lib\site-packages\bokeh\application\handlers\code_runner.py", line 179, in run
    exec(self._code, module.__dict__)
  File "C:\repos\AA%20Data%20Science%20Fridays\event_20191101\awesome-analytics-apps\apps\panel_apps\panel-examples\getting_started\Introduction.ipynb", line 117, in <module>
    "cell_type": "code",
  File "c:\repos\private\awesome-analytics-apps-in-python\.venv\lib\site-packages\panel\viewable.py", line 505, in servable
    self.server_doc(title=title)
  File "c:\repos\private\awesome-analytics-apps-in-python\.venv\lib\site-packages\panel\viewable.py", line 478, in server_doc
    model = self.get_root(doc)
  File "c:\repos\private\awesome-analytics-apps-in-python\.venv\lib\site-packages\panel\viewable.py", line 418, in get_root
    root = self._get_model(doc, comm=comm)
  File "c:\repos\private\awesome-analytics-apps-in-python\.venv\lib\site-packages\panel\layout.py", line 115, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "c:\repos\private\awesome-analytics-apps-in-python\.venv\lib\site-packages\panel\layout.py", line 107, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "c:\repos\private\awesome-analytics-apps-in-python\.venv\lib\site-packages\panel\param.py", line 616, in _get_model
    model = self._inner_layout._get_model(doc, root, parent, comm)
  File "c:\repos\private\awesome-analytics-apps-in-python\.venv\lib\site-packages\panel\layout.py", line 115, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "c:\repos\private\awesome-analytics-apps-in-python\.venv\lib\site-packages\panel\layout.py", line 107, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "c:\repos\private\awesome-analytics-apps-in-python\.venv\lib\site-packages\panel\pane\markup.py", line 51, in _get_model
    model = self._bokeh_model(**self._get_properties())
  File "c:\repos\private\awesome-analytics-apps-in-python\.venv\lib\site-packages\panel\pane\image.py", line 72, in _get_properties
    data = self._img()
  File "c:\repos\private\awesome-analytics-apps-in-python\.venv\lib\site-packages\panel\pane\plot.py", line 85, in _img
    self.object.set_dpi(self.dpi)
  File "c:\repos\private\awesome-analytics-apps-in-python\.venv\lib\site-packages\matplotlib\figure.py", line 986, in set_dpi
    self.dpi = val
  File "c:\repos\private\awesome-analytics-apps-in-python\.venv\lib\site-packages\matplotlib\figure.py", line 477, in _set_dpi
    self.set_size_inches(w, h, forward=forward)
  File "c:\repos\private\awesome-analytics-apps-in-python\.venv\lib\site-packages\matplotlib\figure.py", line 912, in set_size_inches
    manager.resize(int(canvasw), int(canvash))
  File "c:\repos\private\awesome-analytics-apps-in-python\.venv\lib\site-packages\matplotlib\backends\_backend_tk.py", line 532, in resize
    self.canvas._tkcanvas.master.geometry("%dx%d" % (width, height))
  File "C:\Users\masma\AppData\Local\Programs\Python\Python37\lib\tkinter\__init__.py",
line 1841, in wm_geometry
    return self.tk.call('wm', 'geometry', self._w, newGeometry)
_tkinter.TclError: can't invoke "wm" command: application has been destroyed

2019-11-14 05:27:53,399 200 GET /Introduction (::1) 3160.37ms
2019-11-14 05:27:54,101 200 GET /static/js/bokeh.min.js?v=547e7d2591695b654def5914bdd697fa (::1) 680.48ms
2019-11-14 05:27:54,111 200 GET /static/js/bokeh-tables.min.js?v=5f778b8a005d8538b5b13998ec45fc16 (::1) 5.00ms
2019-11-14 05:27:54,115 200 GET /static/js/bokeh-gl.min.js?v=be19384f76795da42f51580e7b5fd473 (::1) 8.01ms
2019-11-14 05:27:54,122 200 GET /static/js/bokeh-widgets.min.js?v=423bf6bb32b8def8b6c9df74817506e4 (::1) 6.00ms
2019-11-14 05:27:54,551 101 GET /Introduction/ws?bokeh-protocol-version=1.0&bokeh-session-id=oC8q3M8YotaXgYwyWIStxIxl1ueL4dAGOQYPhRrEtyDM (::1) 1.00ms
2019-11-14 05:27:54,558 WebSocket connection opened
2019-11-14 05:27:54,559 ServerConnection created
2019-11-14 05:27:54,627 404 GET /favicon.ico (::1) 1.00ms

Interrupted, shutting down
```

#### Solution for Error 1:

Add  

```python
import matplotlib
matplotlib.use("Agg")
```

![image](https://user-images.githubusercontent.com/42288570/68827257-9820a900-06a1-11ea-89d1-f4d678fe4002.png)

### Error 2: ModuleNotFoundError: No module named 'hvplot'

```bash
$ panel serve --show Introduction.ipynb
2019-11-14 05:30:13,547 Starting Bokeh server version 1.3.4 (running on Tornado 6.0.3)
2019-11-14 05:30:13,547 Bokeh app running at: http://localhost:5006/Introduction
2019-11-14 05:30:13,547 Starting Bokeh server with process id: 10380
Column
    [0] Column
        [0] FloatSlider(end=3.0, name='frequency', start=-1.0, value=1.0)
        [1] FloatSlider(end=3.0, name='amplitude', start=-1.0, value=1.0)
        [2] IntSlider(end=100, name='n', start=5, value=200)
    [1] Row
        [0] Matplotlib(Figure, name='interactive00015')
2019-11-14 05:30:16,335 Error running application handler <bokeh.application.handlers.notebook.NotebookHandler object at 0x00000033C0A68C88>: No module named 'hvplot'
File "Introduction.ipynb", line 163, in <module>:
"## Deploying Panels\n", Traceback (most recent call last):
  File "c:\repos\private\awesome-analytics-apps-in-python\.venv\lib\site-packages\bokeh\application\handlers\code_runner.py", line 179, in run
    exec(self._code, module.__dict__)
  File "C:\repos\AA%20Data%20Science%20Fridays\event_20191101\awesome-analytics-apps\apps\panel_apps\panel-examples\getting_started\Introduction.ipynb", line 163, in <module>
    "## Deploying Panels\n",
ModuleNotFoundError: No module named 'hvplot'

2019-11-14 05:30:16,366 200 GET /Introduction (::1) 1567.36ms
2019-11-14 05:30:16,746 101 GET /Introduction/ws?bokeh-protocol-version=1.0&bokeh-session-id=GSMoReK8jZ9NOVxYTDZ4xXJ0GQleMTQa6cCXYYkpFQAa (::1) 47.28ms
2019-11-14 05:30:16,758 WebSocket connection opened
2019-11-14 05:30:16,759 ServerConnection created
```

#### Solution for Error 2:

describe what needs to be pip installed for the examples to work. For the Introduction its.

```python
pip install hvplot
```

**Comment by philippjfr** [comment]
Should be fixed in the latest updates to the section. Will be released later today or tomorrow.
